project-mongo-api by Irina Jekabsone
Technigo/project-mongo-api pull request #141
Opened 2021-05-12 21:54 UTC by Irina-web-dev

You can find this API live on Heroku: https://books-base.herokuapp.com/

2021-05-19 20:01 UTC, NoemiSalome reviewed
Hej Irina!
I was supposed to do Tina's Code, but since we haven't heard from her I guess I'll be doing yours this week - so it was not my fault! Please talk to the manager about this and not me 💁🏼‍♀️ 😉
There wasn't too much code to review this week. But what I saw looks clean, pretty and totally readable! Great job on this! 🤩
On Heruko however I'm getting "Cannot GET /", so you are hiding your pretty endpoints behind that error. Which makes the Sherlock in me suspicious and wondering what's going on behind the scenes 🕵🏼‍♀️ Some puppy or money trading maybe? (I'd be interested in a puppy by the way 🐶)
I think you might be missing the endpoint "/", but I left a comment below. Hope that will solve it.

However I hope you enjoy the backend! It is giving me a bit of a hard time. I am hoping for better times 😅

2021-05-19 20:07 UTC, NoemiSalome requested changes
Hej Irina!
I was supposed to do Tina's Code, but since we haven't heard from her I guess I'll be doing yours this week - so it was not my fault! Please talk to the manager about this and not me 💁🏼‍♀️ 😉
There wasn't too much code to review this week. But what I saw looks clean, pretty and totally readable! Great job on this! 🤩
On Heruko however I'm getting "Cannot GET /", so you are hiding your pretty endpoints behind that error. Which makes the Sherlock in me suspicious and wondering what's going on behind the scenes 🕵🏼‍♀️ Some puppy or money trading maybe? (I'd be interested in a puppy by the way 🐶)
You might be missing the endpoint "/", but I left a comment below. 
However I hope you are enjoying the backend! 🤩

2021-05-20 07:18 UTC, Irina-web-dev commented on server.js
> +
Thank you @NoemiSalome 😊 I totally forgot about express list endpoints 🤷‍♀️ Now it should work properly ✔

2021-05-22 12:47 UTC, KarolCislowski approved these changes
Nice and clean API 🥳

2021-05-22 12:47 UTC, KarolCislowski commented on server.js
> +  bookID: Number,
I think it is no need to send this field to the database when you are using autogenerated _id 🤓

2021-05-22 12:47 UTC, KarolCislowski commented on server.js
> +  }
sweet 🥳

2021-12-14 20:01 UTC, closed without merging