Project Mongo API - Julia Ros
Technigo/project-mongo-api pull request #162
Opened 2021-05-15 11:09 UTC by julialeonieros

https://books-mongodb.herokuapp.com/

2021-05-19 20:06 UTC, CarolineF3 requested changes
Really nice project, well done!✨🎉 It's great that you're using try and catch. All of the endpoints works great except for top10, not sure why.

2021-05-22 19:47 UTC, KarolCislowski approved these changes
Great API 😄

2021-05-22 19:47 UTC, KarolCislowski commented on README.md
> +* '/books/top10' - Get a list of the 10 books with the highest rating
Nice documentation 😸

2021-05-22 19:47 UTC, KarolCislowski commented on server.js
> +    res.json(books)
nice filtering 👍🏻

2021-05-22 19:47 UTC, KarolCislowski commented on server.js
> +  const top10 = await Book.find().sort({ average_rating: -1 }).limit(20).exec()
top 10 and limit 20? 😜

2021-12-14 20:01 UTC, closed without merging