Fethullah week 18 project mongo api
Technigo/project-mongo-api pull request #169
Opened 2021-05-16 10:58 UTC by FD000

2021-05-23 11:40 UTC, KarolCislowski approved these changes
Nice API 👍🏻

2021-05-23 11:40 UTC, KarolCislowski commented on README.md
> +7) .../highestrated - List top 20 highest rated books
nice documentation 👍🏻

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +newAuthor.save() */
remember to clean your code from unused code.

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +  bookID: Number,
you do not need to pass the old id because mongoose will provide a new one.

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +let myAPI
why you created your variable outside the endpoint?

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +// #6 Ratings filter (GÖR en select)
remember to only use English in your code.

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +  myAPI = await Book.find({ num_pages: { $gte: pages}});
👍🏻

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +  myAPI = await Book.find({ num_pages: { $lte: pages}});
👍🏻

2021-05-23 11:40 UTC, KarolCislowski commented on server copy 2.js
> +    res.status(400).json({ error: 'Invalid request'})
nice error handeling.

2021-05-26 21:11 UTC, tuttibalutti requested changes
Great job, Fethullah! I really liked your API and the documentation of it🤩  It seems like you have three different versions of you code: server copy.js, server copy 2.js and the server.js (which I guess is the right one?). I suggest that you remove those copies from your folder to minimize future confusion👀  Well done!

2021-05-26 21:11 UTC, tuttibalutti commented on server.js
> +  myAPI = await Book.find({ num_pages: { $gte: pages}});
Cool that you use the aggregation pipeline operator👌

2021-12-14 20:01 UTC, closed without merging