Project 18 - Caroline Fahlgren
Technigo/project-mongo-api pull request #171
Opened 2021-05-16 11:51 UTC by CarolineF3

https://mongo-api-carolinef.herokuapp.com/

2021-05-18 15:52 UTC, Pauan8 approved these changes
A nice well structured project! 💯 
Unfortunatly the employed heroku API didn't work for me, so you should look at that.

2021-05-18 15:52 UTC, Pauan8 commented on README.md
> +https://mongo-api-carolinef.herokuapp.com/
I could not get any data from the endpoints. It all said "something went wrong"

2021-05-18 15:52 UTC, Pauan8 commented on server.js
> +      .limit(10);
Nice pagination :)

2021-05-18 15:52 UTC, Pauan8 commented on server.js
> +    res.status(400).json({ error: "Something went wrong", details: error });
This error line is used a lot, it could be an idea to put it in a function and call it when needed ^^

2021-05-18 15:52 UTC, Pauan8 commented on data/server.js
> +});
What is this file doing in this project?

2021-05-23 12:01 UTC, KarolCislowski requested changes
Please check your DB connection because your API returns error all the time 😭

2021-06-12 12:44 UTC, KarolCislowski approved these changes
Nice API!

2021-12-14 20:01 UTC, closed without merging