Week 18 Mongo API
Technigo/project-mongo-api pull request #176
Opened 2021-05-16 15:31 UTC by Yennie-Leek

This week I havent had time to work omn the project as much. 
I did get it to work and could see the data in Local host, but when trying to deploy, its not working. 
Will fix it in the future.

2021-05-19 22:50 UTC, idasylven requested changes
I am quite impressed you actually managed to get half way though this project - I know what a hectic week you had 🥵  And deployment was the hardest part, no doubt about it! 🔄  🔙  🔚  🤯

When you get the chance, these are the requested bullet points necessary to meet the project brief: 

General requirements: 
- Deploy the API to Heroku or similar hosting service.
- Deploy the database using Mongo cloud or similar.

Blue level requirements:
- The API should have at least 2 routes.
- A minimum of one endpoint to return a single result (single element).

Hopefully deployment will be a piece of cake after doing it again this week 🍰 🤞🏻  And creating just one more endpoint returning a single result you will do in no time 😎

2021-05-21 14:28 UTC, Yennie-Leek commented
Added more endpoints and got the deployment to work. 
[https://week18mongoapi.herokuapp.com](url)

2021-05-23 13:23 UTC, KarolCislowski approved these changes
Nice API 👍🏻

2021-05-23 13:23 UTC, KarolCislowski commented on README.md
> +
short documentation would be nice 🤓

2021-05-23 13:23 UTC, KarolCislowski commented on server.js
> +  const singleShow = await NetflixData.findById(showId)
👍🏻

2021-12-14 19:56 UTC, closed without merging