week 18 - noemi
Technigo/project-mongo-api pull request #187
Opened 2021-05-16 21:21 UTC by NoemiSalome

2021-05-19 17:19 UTC, honkoan requested changes
Hi lovely teammate Noemi! 🦊😃 

I can see only an empty array or error messages (error messages are working well 🥳) when I'm trying to see your endpoints. I tried to figure out why it is so, but I couldn't. That's the reason I'm requesting changes!

2021-05-23 15:46 UTC, KarolCislowski approved these changes
Nice API 👍🏻

2021-05-23 15:46 UTC, KarolCislowski commented on README.md
> +https://project-week-18.herokuapp.com/
Short documentation would be nice 👍🏻

2021-05-23 15:46 UTC, KarolCislowski commented on server.js
> +  bookID: Number,
Why do you need both bookId and _id?

2021-05-23 15:46 UTC, KarolCislowski commented on server.js
> +}
Nice filtering 👍🏻

2021-12-14 19:56 UTC, closed without merging