Mongo-db-Nazanin
Technigo/project-mongo-api pull request #197
Opened 2021-07-01 17:05 UTC by nazi-pira

2021-07-04 17:00 UTC, KarolCislowski requested changes
You need to provide the Heroku link to your project.

2021-07-07 18:25 UTC, KarolCislowski requested changes
You need to seed your Atlas because your Api returns en empty json ![image](https://user-images.githubusercontent.com/50926159/124810173-4ce79800-df61-11eb-8f57-ef3e2cfaea81.png)

2021-07-30 18:41 UTC, nazi-pira commented
fixed

2021-09-02 13:55 UTC, HIPPIEKICK approved these changes

2021-12-14 19:57 UTC, closed without merging